# Generated by Django 3.2.13 on 2022-05-02 17:44

from django.db import migrations

ALTER_PARKING_PERMIT_ID_SEQ_SQL = """
ALTER SEQUENCE parking_permits_parkingpermit_id_seq START WITH 80000000;
ALTER SEQUENCE parking_permits_parkingpermit_id_seq RESTART;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(ALTER_PARKING_PERMIT_ID_SEQ_SQL, migrations.RunSQL.noop)
    ]
