# Generated by Django 3.2.13 on 2022-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0002_permit_id_seq_start_val"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="language",
            field=models.CharField(
                choices=[("fi", "Finnish"), ("sv", "Swedish"), ("en", "English")],
                default="fi",
                max_length=10,
                verbose_name="Language",
            ),
        ),
    ]
