# Generated by Django 3.2 on 2022-04-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0023_parkingpermit_order_add_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingpermit",
            name="vehicle_changed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="parkingpermit",
            name="vehicle_changed_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vehicle changed date"
            ),
        ),
    ]
