# Generated by Django 3.2.12 on 2022-04-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_permits", "0025_update_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parkingpermit",
            name="order",
        ),
        migrations.AddField(
            model_name="order",
            name="permits",
            field=models.ManyToManyField(
                related_name="orders",
                to="parking_permits.ParkingPermit",
                verbose_name="permits",
            ),
        ),
    ]
